name: ✨ Feature Request
description: Suggest a new feature or enhancement for the Deno MCP Server
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see.
      placeholder: What feature would you like to see added?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you want this feature? What problem does it solve?
      placeholder: |
        - What's the use case for this feature?
        - What problem would it solve?
        - How would it improve your workflow?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Describe your ideal solution:
        - What should the API look like?
        - How should users interact with it?
        - What configuration options should be available?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Are there any alternative solutions or workarounds you've considered?
      placeholder: |
        - Other approaches you've considered
        - Existing tools or features that partially solve this
        - Workarounds you're currently using

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would improve my workflow"
        - "High - Essential for my use case"
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        ```typescript
        // Example usage
        ```
      render: typescript

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request.
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please check all that apply
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear use case for this feature
          required: true
        - label: I am willing to help test this feature if implemented
          required: false
